@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiZ3ZlcmFAdXYubXgiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9naXZlbm5hbWUiOiJQYWxlIFVwZGF0ZWQiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbmlzdHJhZG9yIiwiaWlzIjoiU2Vydmlkb3JGZWlKV1QiLCJhdWQiOiJDbGllbnRlc0ZlaUpXVCIsImlhdCI6MTc2NDY1NjYwMSwiZXhwIjoxNzY0NjU3ODAxfQ.BxAbUzbxh7Sl4naM7T-mFL9vXj9u8I9fuKwNyBqnCHs

POST http://localhost:3000/api/archivos
Content-Type: multipart/form-data; boundary=----XXX
Authorization: Bearer {{token}}

------XXX
Content-Disposition: form-data; name="file"; filename="valida.jpg"
Content-Type: image/jpg

< ./assets/valida.jpg
------XXX--

###
GET http://localhost:3000/api/archivos
Authorization: Bearer {{token}}

###
GET http://localhost:3000/api/archivos/2
Authorization: Bearer {{token}}

###
GET http://localhost:3000/api/archivos/5/detalle
Authorization: Bearer {{token}}

###
PUT http://localhost:3000/api/archivos/10
Content-Type: multipart/form-data; boundary=----XXX
Authorization: Bearer {{token}}

------XXX
Content-Disposition: form-data; name="file"; filename="valida.jpg"
Content-Type: image/jpg

< ./assets/valida.jpg
------XXX--

###
DELETE http://localhost:3000/api/archivos/19
Authorization: Bearer {{token}}