@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiZ3ZlcmFAdXYubXgiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9naXZlbm5hbWUiOiJHdWlsbGVybW8gVmVyYSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluaXN0cmFkb3IiLCJpaXMiOiJTZXJ2aWRvckZlaUpXVCIsImF1ZCI6IkNsaWVudGVzRmVpSldUIiwiaWF0IjoxNzYzODI5NzA1LCJleHAiOjE3NjM4MzA5MDV9.1Its7W_3QMhy0RycRyw3cKbRUusUSiaSPz3S_lOXY7E

POST http://localhost:3000/api/auth
Content-Type: application/json

{
    "email": "gvera@uv.mx",
    "password": "patito"
}   

###
GET http://localhost:3000/api/categorias
Authorization: Bearer {{ token }}

###

POST http://localhost:3000/api/auth
Content-Type: application/json

{
  "email": "patito@uv.mx",
  "password": "patito"
}

###

GET http://localhost:3000/api/auth/tiempo
Authorization: Bearer {{ token }}

###

GET http://localhost:3000/api/roles
Content-Type: application/json
Authorization: Bearer {{ token }}

###