@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiZ3ZlcmFAdXYubXgiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9naXZlbm5hbWUiOiJQYWxlIFVwZGF0ZWQiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbmlzdHJhZG9yIiwiaWlzIjoiU2Vydmlkb3JGZWlKV1QiLCJhdWQiOiJDbGllbnRlc0ZlaUpXVCIsImlhdCI6MTc2NDY0Njg0OCwiZXhwIjoxNzY0NjQ4MDQ4fQ.KItreZJVnMlhqj4IZ-kziNtJp199HxlxZ1afDw0O6uw

###
GET http://localhost:3000/api/productos
Authorization: Bearer {{ token }}

###
GET http://localhost:3000/api/productos?s=<script>alert('hack')</script>
Authorization: Bearer {{ token }}

###
GET http://localhost:3000/api/productos/5
Authorization: Bearer {{ token }}

###
POST http://localhost:3000/api/productos
Content-Type: application/json
Authorization: Bearer {{ token }}

{
    "titulo": "Producto de prueba",
    "descripcion": "Este es un producto de prueba",
    "precio": 99999999.99,
    "archivoid": 8
}

###
PUT http://localhost:3000/api/productos/404
Content-Type: application/json
Authorization: Bearer {{ token }}

{
    "titulo": "Producto de prueba editado",
    "descripcion": "Este es un producto de prueba editado",
    "precio": 200,
    "archivoid": 8
}

###
DELETE http://localhost:3000/api/productos/null
Authorization: Bearer {{ token }}

###
POST http://localhost:3000/api/productos/136/categoria
Content-Type: application/json
Authorization: Bearer {{ token }}

{
  "categoriaid": "19"
}

###
DELETE http://localhost:3000/api/productos/5/categoria/2
Authorization: Bearer {{ token }}