@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiZ3ZlcmFAdXYubXgiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9naXZlbm5hbWUiOiJHdWlsbGVybW8gVmVyYSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluaXN0cmFkb3IiLCJpaXMiOiJTZXJ2aWRvckZlaUpXVCIsImF1ZCI6IkNsaWVudGVzRmVpSldUIiwiaWF0IjoxNzY0MTE4NTU5LCJleHAiOjE3NjQxMTk3NTl9.0dq9Zc7wy1bq8xpO8Wa1NztF137VnpDB0Y8MvgPCqLs

###
GET http://localhost:3000/api/productos
Authorization: Bearer {{ token }}

###
GET http://localhost:3000/api/productos?s=<script>alert('hack')</script>
Authorization: Bearer {{ token }}

###
GET http://localhost:3000/api/productos/5
Authorization: Bearer {{ token }}

###
POST http://localhost:3000/api/productos
Content-Type: application/json
Authorization: Bearer {{ token }}

{
    "titulo": "Producto de prueba",
    "descripcion": "Este es un producto de prueba",
    "precio": 150,
    "archivoid": 8
}

###
PUT http://localhost:3000/api/productos/404
Content-Type: application/json
Authorization: Bearer {{ token }}

{
    "titulo": "Producto de prueba editado",
    "descripcion": "Este es un producto de prueba editado",
    "precio": 200,
    "archivoid": 8
}

###
DELETE http://localhost:3000/api/productos/null
Authorization: Bearer {{ token }}

###
POST http://localhost:3000/api/productos/5/categoria
Content-Type: application/json
Authorization: Bearer {{ token }}

{
  "categoriaid": "5"
}

###
DELETE http://localhost:3000/api/productos/5/categoria/2
Authorization: Bearer {{ token }}