@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiZ3ZlcmFAdXYubXgiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9naXZlbm5hbWUiOiJHdWlsbGVybW8gVmVyYSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluaXN0cmFkb3IiLCJpaXMiOiJTZXJ2aWRvckZlaUpXVCIsImF1ZCI6IkNsaWVudGVzRmVpSldUIiwiaWF0IjoxNzY0MTIxODczLCJleHAiOjE3NjQxMjMwNzN9.P3StfXteHdtbYrE9MqS8I923whBWDvsxeeYf2ZHi03A

GET http://localhost:3000/api/usuarios
Authorization: Bearer {{token}}

###
GET http://localhost:3000/api/usuarios/gvera@uv.mx
Authorization: Bearer {{token}}

###
POST http://localhost:3000/api/usuarios
Content-Type: application/json

{
    "email": "pale@gmail.com",
    "password": "securepassword",
    "nombre": "Pale",
    "rol": "Usuario"
}

###
PUT http://localhost:3000/api/usuarios/gvera@uv.mx
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "email": "gvera@uv.mx",
    "password": "patito",
    "nombre": "Pale Updated",
    "rol": "Administrador"
}

###
DELETE http://localhost:3000/api/usuarios/pale@gmail.com
Authorization: Bearer {{token}}